package com.pmlp.edutask.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val EduPrimary             = Color(0xFF4355B9)
val EduOnPrimary           = Color.White
val EduPrimaryContainer    = Color(0xFFDEE0FF)
val EduOnPrimaryContainer  = Color(0xFF00105C)
val EduSecondary           = Color(0xFF5B5D72)
val EduOnSecondary         = Color.White
val EduSecondaryContainer  = Color(0xFFE0E1F9)
val EduOnSecondaryContainer = Color(0xFF181A2C)
val EduTertiary            = Color(0xFF77536D)
val EduOnTertiary          = Color.White
val EduTertiaryContainer   = Color(0xFFFFD7F1)
val EduOnTertiaryContainer = Color(0xFF2D1228)
val EduError               = Color(0xFFBA1A1A)
val EduOnError             = Color.White
val EduErrorContainer      = Color(0xFFFFDAD6)
val EduOnErrorContainer    = Color(0xFF93000A)
val EduBackground          = Color(0xFFFEFBFF)
val EduOnBackground        = Color(0xFF1B1B1F)
val EduSurface             = Color(0xFFFEFBFF)
val EduOnSurface           = Color(0xFF1B1B1F)
val EduSurfaceVariant      = Color(0xFFE3E1EC)
val EduOnSurfaceVariant    = Color(0xFF46464F)
val EduOutline             = Color(0xFF777680)
val EduOutlineVariant      = Color(0xFFC7C5D0)
val EduScrim               = Color(0xFF000000)
val EduInverseSurface      = Color(0xFF313034)
val EduInverseOnSurface    = Color(0xFFF3EFF4)
val EduInversePrimary      = Color(0xFFBBC2FF)
val EduSurfaceTint         = Color(0xFF4355B9)
val EduSurfaceContainerLowest  = Color(0xFFFFFBFF)
val EduSurfaceContainerLow     = Color(0xFFF5F2FB)
val EduSurfaceContainer        = Color(0xFFEFECF5)
val EduSurfaceContainerHigh    = Color(0xFFE9E7EF)
val EduSurfaceContainerHighest = Color(0xFFE4E1EA)

// Dark palette
val EduPrimaryDark             = Color(0xFFBBC2FF)
val EduOnPrimaryDark           = Color(0xFF08218A)
val EduPrimaryContainerDark    = Color(0xFF293CA0)
val EduOnPrimaryContainerDark  = Color(0xFFDEE0FF)
val EduSecondaryDark           = Color(0xFFC4C5DD)
val EduOnSecondaryDark         = Color(0xFF2D2F42)
val EduSecondaryContainerDark  = Color(0xFF434659)
val EduOnSecondaryContainerDark = Color(0xFFE0E1F9)
val EduTertiaryDark            = Color(0xFFE5B9D5)
val EduOnTertiaryDark          = Color(0xFF44263D)
val EduTertiaryContainerDark   = Color(0xFF5D3C54)
val EduOnTertiaryContainerDark = Color(0xFFFFD7F1)
val EduErrorDark               = Color(0xFFFFB4AB)
val EduOnErrorDark             = Color(0xFF690005)
val EduErrorContainerDark      = Color(0xFF93000A)
val EduOnErrorContainerDark    = Color(0xFFFFDAD6)
val EduBackgroundDark          = Color(0xFF1B1B1F)
val EduOnBackgroundDark        = Color(0xFFE5E1E6)
val EduSurfaceDark             = Color(0xFF1B1B1F)
val EduOnSurfaceDark           = Color(0xFFE5E1E6)
val EduSurfaceVariantDark      = Color(0xFF46464F)
val EduOnSurfaceVariantDark    = Color(0xFFC7C5D0)
val EduOutlineDark             = Color(0xFF918F9A)
val EduOutlineVariantDark      = Color(0xFF46464F)
val EduInverseSurfaceDark      = Color(0xFFE5E1E6)
val EduInverseOnSurfaceDark    = Color(0xFF313034)
val EduInversePrimaryDark      = Color(0xFF4355B9)
val EduSurfaceContainerLowestDark  = Color(0xFF0F0F14)
val EduSurfaceContainerLowDark     = Color(0xFF1B1B1F)
val EduSurfaceContainerDark        = Color(0xFF201F23)
val EduSurfaceContainerHighDark    = Color(0xFF2B2930)
val EduSurfaceContainerHighestDark = Color(0xFF36343B)