package com.pmlp.edutask.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val EduPrimary             = Color(0xFF8B4F26)
val EduOnPrimary           = Color.White
val EduPrimaryContainer    = Color(0xFFFFDBC8)
val EduOnPrimaryContainer  = Color(0xFF6F3810)
val EduSecondary           = Color(0xFF755847)
val EduOnSecondary         = Color.White
val EduSecondaryContainer  = Color(0xFFFFDBC8)
val EduOnSecondaryContainer = Color(0xFF5C4131)
val EduTertiary            = Color(0xFF616033)
val EduOnTertiary          = Color.White
val EduTertiaryContainer   = Color(0xFFE8E5AC)
val EduOnTertiaryContainer = Color(0xFF49491E)
val EduError               = Color(0xFFBA1A1A)
val EduOnError             = Color.White
val EduErrorContainer      = Color(0xFFFFDAD6)
val EduOnErrorContainer    = Color(0xFF93000A)
val EduBackground          = Color(0xFFFFF8F5)
val EduOnBackground        = Color(0xFF221A15)
val EduSurface             = Color(0xFFFFF8F5)
val EduOnSurface           = Color(0xFF221A15)
val EduSurfaceVariant      = Color(0xFFF4DED3)
val EduOnSurfaceVariant    = Color(0xFF52443C)
val EduOutline             = Color(0xFF85746B)
val EduOutlineVariant      = Color(0xFFD7C2B8)
val EduScrim               = Color(0xFF000000)
val EduInverseSurface      = Color(0xFF382E29)
val EduInverseOnSurface    = Color(0xFFFFEDE5)
val EduInversePrimary      = Color(0xFFFFB68A)
val EduSurfaceTint         = Color(0xFF8B4F26)
val EduSurfaceContainerLowest  = Color(0xFFFFFFFF)
val EduSurfaceContainerLow     = Color(0xFFFFF1EA)
val EduSurfaceContainer        = Color(0xFFFCEAE2)
val EduSurfaceContainerHigh    = Color(0xFFF6E5DD)
val EduSurfaceContainerHighest = Color(0xFFF0DFD7)

// Dark palette
val EduPrimaryDark             = Color(0xFFFFB68A)
val EduOnPrimaryDark           = Color(0xFF522300)
val EduPrimaryContainerDark    = Color(0xFF6F3810)
val EduOnPrimaryContainerDark  = Color(0xFFFFDBC8)
val EduSecondaryDark           = Color(0xFFE5BFA9)
val EduOnSecondaryDark         = Color(0xFF432B1C)
val EduSecondaryContainerDark  = Color(0xFF5C4131)
val EduOnSecondaryContainerDark = Color(0xFFFFDBC8)
val EduTertiaryDark            = Color(0xFFCBC992)
val EduOnTertiaryDark          = Color(0xFF323209)
val EduTertiaryContainerDark   = Color(0xFF49491E)
val EduOnTertiaryContainerDark = Color(0xFFE8E5AC)
val EduErrorDark               = Color(0xFFFFB4AB)
val EduOnErrorDark             = Color(0xFF690005)
val EduErrorContainerDark      = Color(0xFF93000A)
val EduOnErrorContainerDark    = Color(0xFFFFDAD6)
val EduBackgroundDark          = Color(0xFF1A120D)
val EduOnBackgroundDark        = Color(0xFFF0DFD7)
val EduSurfaceDark             = Color(0xFF1A120D)
val EduOnSurfaceDark           = Color(0xFFF0DFD7)
val EduSurfaceVariantDark      = Color(0xFF52443C)
val EduOnSurfaceVariantDark    = Color(0xFFD7C2B8)
val EduOutlineDark             = Color(0xFF9F8D84)
val EduOutlineVariantDark      = Color(0xFF52443C)
val EduInverseSurfaceDark      = Color(0xFFF0DFD7)
val EduInverseOnSurfaceDark    = Color(0xFF382E29)
val EduInversePrimaryDark      = Color(0xFF8B4F26)
val EduSurfaceContainerLowestDark  = Color(0xFF140D08)
val EduSurfaceContainerLowDark     = Color(0xFF221A15)
val EduSurfaceContainerDark        = Color(0xFF261E19)
val EduSurfaceContainerHighDark    = Color(0xFF312823)
val EduSurfaceContainerHighestDark = Color(0xFF3D332D)